export const POST_LIST_DATA_REQUEST = 'POST_LIST_DATA_REQUEST';
export const POST_LIST_DATA_SUCCESS = 'POST_LIST_DATA_SUCCESS';

export const POST_LIST_PAGINATION_PAGE_REQUEST = 'POST_LIST_PAGINATION_PAGE_REQUEST';
export const POST_LIST_PAGINATION_PAGE_SUCCESS = 'POST_LIST_PAGINATION_PAGE_SUCCESS';

export const POST_LIST_PAGINATION_LIMIT_REQUEST = 'POST_LIST_PAGINATION_LIMIT_REQUEST';
export const POST_LIST_PAGINATION_LIMIT_SUCCESS = 'POST_LIST_PAGINATION_LIMIT_SUCCESS';

export const POST_LIST_PAGINATION_TOTAL_REQUEST = 'POST_LIST_PAGINATION_TOTAL_REQUEST';
export const POST_LIST_PAGINATION_TOTAL_SUCCESS = 'POST_LIST_PAGINATION_TOTAL_SUCCESS';

export const POST_LIST_FILTER_SORT_DIRECTION_REQUEST = 'POST_LIST_FILTER_SORT_DIRECTION_REQUEST';
export const POST_LIST_FILTER_SORT_DIRECTION_SUCCESS = 'POST_LIST_FILTER_SORT_DIRECTION_SUCCESS';

export const POST_LIST_FILTER_SORT_BY_REQUEST = 'POST_LIST_FILTER_SORT_BY_REQUEST';
export const POST_LIST_FILTER_SORT_BY_SUCCESS = 'POST_LIST_FILTER_SORT_BY_SUCCESS';

export const POST_LIST_FILTER_Q_REQUEST = 'POST_LIST_FILTER_Q_REQUEST';
export const POST_LIST_FILTER_Q_SUCCESS = 'POST_LIST_FILTER_Q_SUCCESS';

export const POST_LIST_FILTER_Q_TEMP_REQUEST = 'POST_LIST_FILTER_Q_TEMP_REQUEST';
export const POST_LIST_FILTER_Q_TEMP_SUCCESS = 'POST_LIST_FILTER_Q_TEMP_SUCCESS';

export const POST_LIST_LOADING_REQUEST = 'POST_LIST_LOADING_REQUEST';
export const POST_LIST_LOADING_SUCCESS = 'POST_LIST_LOADING_SUCCESS';

export const POST_SHOW_DATA_REQUEST = 'POST_SHOW_DATA_REQUEST';
export const POST_SHOW_DATA_SUCCESS = 'POST_SHOW_DATA_SUCCESS';

export const POST_SHOW_LOADING_REQUEST = 'POST_SHOW_LOADING_REQUEST';
export const POST_SHOW_LOADING_SUCCESS = 'POST_SHOW_LOADING_SUCCESS';

export const POST_CREATE_DATA_REQUEST = 'POST_CREATE_DATA_REQUEST';
export const POST_CREATE_DATA_SUCCESS = 'POST_CREATE_DATA_SUCCESS';

export const POST_CREATE_LOADING_REQUEST = 'POST_CREATE_LOADING_REQUEST';
export const POST_CREATE_LOADING_SUCCESS = 'POST_CREATE_LOADING_SUCCESS';

export const POST_UPDATE_DATA_REQUEST = 'POST_UPDATE_DATA_REQUEST';
export const POST_UPDATE_DATA_SUCCESS = 'POST_UPDATE_DATA_SUCCESS';

export const POST_UPDATE_LOADING_REQUEST = 'POST_UPDATE_LOADING_REQUEST';
export const POST_UPDATE_LOADING_SUCCESS = 'POST_UPDATE_LOADING_SUCCESS';

export const POST_DELETE_DATA_REQUEST = 'POST_DELETE_DATA_REQUEST';
export const POST_DELETE_DATA_SUCCESS = 'POST_DELETE_DATA_SUCCESS';

export const POST_DELETE_LOADING_REQUEST = 'POST_DELETE_LOADING_REQUEST';
export const POST_DELETE_LOADING_SUCCESS = 'POST_DELETE_LOADING_SUCCESS';
