export const SETTING_SHOW_DATA_REQUEST = 'SETTING_SHOW_DATA_REQUEST';
export const SETTING_SHOW_DATA_SUCCESS = 'SETTING_SHOW_DATA_SUCCESS';

export const SETTING_SHOW_LOADING_REQUEST = 'SETTING_SHOW_LOADING_REQUEST';
export const SETTING_SHOW_LOADING_SUCCESS = 'SETTING_SHOW_LOADING_SUCCESS';

export const SETTING_UPDATE_DATA_REQUEST = 'SETTING_UPDATE_DATA_REQUEST';
export const SETTING_UPDATE_DATA_SUCCESS = 'SETTING_UPDATE_DATA_SUCCESS';

export const SETTING_UPDATE_LOADING_REQUEST = 'SETTING_UPDATE_LOADING_REQUEST';
export const SETTING_UPDATE_LOADING_SUCCESS = 'SETTING_UPDATE_LOADING_SUCCESS';
