export const USER_LIST_DATA_REQUEST = 'USER_LIST_DATA_REQUEST';
export const USER_LIST_DATA_SUCCESS = 'USER_LIST_DATA_SUCCESS';

export const USER_LIST_PAGINATION_PAGE_REQUEST = 'USER_LIST_PAGINATION_PAGE_REQUEST';
export const USER_LIST_PAGINATION_PAGE_SUCCESS = 'USER_LIST_PAGINATION_PAGE_SUCCESS';

export const USER_LIST_PAGINATION_LIMIT_REQUEST = 'USER_LIST_PAGINATION_LIMIT_REQUEST';
export const USER_LIST_PAGINATION_LIMIT_SUCCESS = 'USER_LIST_PAGINATION_LIMIT_SUCCESS';

export const USER_LIST_PAGINATION_TOTAL_REQUEST = 'USER_LIST_PAGINATION_TOTAL_REQUEST';
export const USER_LIST_PAGINATION_TOTAL_SUCCESS = 'USER_LIST_PAGINATION_TOTAL_SUCCESS';

export const USER_LIST_FILTER_SORT_DIRECTION_REQUEST = 'USER_LIST_FILTER_SORT_DIRECTION_REQUEST';
export const USER_LIST_FILTER_SORT_DIRECTION_SUCCESS = 'USER_LIST_FILTER_SORT_DIRECTION_SUCCESS';

export const USER_LIST_FILTER_SORT_BY_REQUEST = 'USER_LIST_FILTER_SORT_BY_REQUEST';
export const USER_LIST_FILTER_SORT_BY_SUCCESS = 'USER_LIST_FILTER_SORT_BY_SUCCESS';

export const USER_LIST_FILTER_Q_REQUEST = 'USER_LIST_FILTER_Q_REQUEST';
export const USER_LIST_FILTER_Q_SUCCESS = 'USER_LIST_FILTER_Q_SUCCESS';

export const USER_LIST_FILTER_Q_TEMP_REQUEST = 'USER_LIST_FILTER_Q_TEMP_REQUEST';
export const USER_LIST_FILTER_Q_TEMP_SUCCESS = 'USER_LIST_FILTER_Q_TEMP_SUCCESS';

export const USER_LIST_LOADING_REQUEST = 'USER_LIST_LOADING_REQUEST';
export const USER_LIST_LOADING_SUCCESS = 'USER_LIST_LOADING_SUCCESS';

export const USER_SHOW_DATA_REQUEST = 'USER_SHOW_DATA_REQUEST';
export const USER_SHOW_DATA_SUCCESS = 'USER_SHOW_DATA_SUCCESS';

export const USER_SHOW_LOADING_REQUEST = 'USER_SHOW_LOADING_REQUEST';
export const USER_SHOW_LOADING_SUCCESS = 'USER_SHOW_LOADING_SUCCESS';

export const USER_CREATE_DATA_REQUEST = 'USER_CREATE_DATA_REQUEST';
export const USER_CREATE_DATA_SUCCESS = 'USER_CREATE_DATA_SUCCESS';

export const USER_CREATE_LOADING_REQUEST = 'USER_CREATE_LOADING_REQUEST';
export const USER_CREATE_LOADING_SUCCESS = 'USER_CREATE_LOADING_SUCCESS';

export const USER_UPDATE_DATA_REQUEST = 'USER_UPDATE_DATA_REQUEST';
export const USER_UPDATE_DATA_SUCCESS = 'USER_UPDATE_DATA_SUCCESS';

export const USER_UPDATE_LOADING_REQUEST = 'USER_UPDATE_LOADING_REQUEST';
export const USER_UPDATE_LOADING_SUCCESS = 'USER_UPDATE_LOADING_SUCCESS';

export const USER_DELETE_DATA_REQUEST = 'USER_DELETE_DATA_REQUEST';
export const USER_DELETE_DATA_SUCCESS = 'USER_DELETE_DATA_SUCCESS';

export const USER_DELETE_LOADING_REQUEST = 'USER_DELETE_LOADING_REQUEST';
export const USER_DELETE_LOADING_SUCCESS = 'USER_DELETE_LOADING_SUCCESS';
