export const AUTH_CURRENT_DATA_REQUEST = 'AUTH_CURRENT_DATA_REQUEST';
export const AUTH_CURRENT_DATA_SUCCESS = 'AUTH_CURRENT_DATA_SUCCESS';

export const AUTH_CURRENT_TOKEN_REQUEST = 'AUTH_CURRENT_TOKEN_REQUEST';
export const AUTH_CURRENT_TOKEN_SUCCESS = 'AUTH_CURRENT_TOKEN_SUCCESS';
