export const CATEGORY_LIST_DATA_REQUEST = 'CATEGORY_LIST_DATA_REQUEST';
export const CATEGORY_LIST_DATA_SUCCESS = 'CATEGORY_LIST_DATA_SUCCESS';

export const CATEGORY_LIST_PAGINATION_PAGE_REQUEST = 'CATEGORY_LIST_PAGINATION_PAGE_REQUEST';
export const CATEGORY_LIST_PAGINATION_PAGE_SUCCESS = 'CATEGORY_LIST_PAGINATION_PAGE_SUCCESS';

export const CATEGORY_LIST_PAGINATION_LIMIT_REQUEST = 'CATEGORY_LIST_PAGINATION_LIMIT_REQUEST';
export const CATEGORY_LIST_PAGINATION_LIMIT_SUCCESS = 'CATEGORY_LIST_PAGINATION_LIMIT_SUCCESS';

export const CATEGORY_LIST_PAGINATION_TOTAL_REQUEST = 'CATEGORY_LIST_PAGINATION_TOTAL_REQUEST';
export const CATEGORY_LIST_PAGINATION_TOTAL_SUCCESS = 'CATEGORY_LIST_PAGINATION_TOTAL_SUCCESS';

export const CATEGORY_LIST_FILTER_SORT_DIRECTION_REQUEST = 'CATEGORY_LIST_FILTER_SORT_DIRECTION_REQUEST';
export const CATEGORY_LIST_FILTER_SORT_DIRECTION_SUCCESS = 'CATEGORY_LIST_FILTER_SORT_DIRECTION_SUCCESS';

export const CATEGORY_LIST_FILTER_SORT_BY_REQUEST = 'CATEGORY_LIST_FILTER_SORT_BY_REQUEST';
export const CATEGORY_LIST_FILTER_SORT_BY_SUCCESS = 'CATEGORY_LIST_FILTER_SORT_BY_SUCCESS';

export const CATEGORY_LIST_FILTER_Q_REQUEST = 'CATEGORY_LIST_FILTER_Q_REQUEST';
export const CATEGORY_LIST_FILTER_Q_SUCCESS = 'CATEGORY_LIST_FILTER_Q_SUCCESS';

export const CATEGORY_LIST_FILTER_Q_TEMP_REQUEST = 'CATEGORY_LIST_FILTER_Q_TEMP_REQUEST';
export const CATEGORY_LIST_FILTER_Q_TEMP_SUCCESS = 'CATEGORY_LIST_FILTER_Q_TEMP_SUCCESS';

export const CATEGORY_LIST_LOADING_REQUEST = 'CATEGORY_LIST_LOADING_REQUEST';
export const CATEGORY_LIST_LOADING_SUCCESS = 'CATEGORY_LIST_LOADING_SUCCESS';

export const CATEGORY_SHOW_DATA_REQUEST = 'CATEGORY_SHOW_DATA_REQUEST';
export const CATEGORY_SHOW_DATA_SUCCESS = 'CATEGORY_SHOW_DATA_SUCCESS';

export const CATEGORY_SHOW_LOADING_REQUEST = 'CATEGORY_SHOW_LOADING_REQUEST';
export const CATEGORY_SHOW_LOADING_SUCCESS = 'CATEGORY_SHOW_LOADING_SUCCESS';

export const CATEGORY_CREATE_DATA_REQUEST = 'CATEGORY_CREATE_DATA_REQUEST';
export const CATEGORY_CREATE_DATA_SUCCESS = 'CATEGORY_CREATE_DATA_SUCCESS';

export const CATEGORY_CREATE_LOADING_REQUEST = 'CATEGORY_CREATE_LOADING_REQUEST';
export const CATEGORY_CREATE_LOADING_SUCCESS = 'CATEGORY_CREATE_LOADING_SUCCESS';

export const CATEGORY_UPDATE_DATA_REQUEST = 'CATEGORY_UPDATE_DATA_REQUEST';
export const CATEGORY_UPDATE_DATA_SUCCESS = 'CATEGORY_UPDATE_DATA_SUCCESS';

export const CATEGORY_UPDATE_LOADING_REQUEST = 'CATEGORY_UPDATE_LOADING_REQUEST';
export const CATEGORY_UPDATE_LOADING_SUCCESS = 'CATEGORY_UPDATE_LOADING_SUCCESS';

export const CATEGORY_DELETE_DATA_REQUEST = 'CATEGORY_DELETE_DATA_REQUEST';
export const CATEGORY_DELETE_DATA_SUCCESS = 'CATEGORY_DELETE_DATA_SUCCESS';

export const CATEGORY_DELETE_LOADING_REQUEST = 'CATEGORY_DELETE_LOADING_REQUEST';
export const CATEGORY_DELETE_LOADING_SUCCESS = 'CATEGORY_DELETE_LOADING_SUCCESS';
