export const PROFILE_SHOW_DATA_REQUEST = 'PROFILE_SHOW_DATA_REQUEST';
export const PROFILE_SHOW_DATA_SUCCESS = 'PROFILE_SHOW_DATA_SUCCESS';

export const PROFILE_SHOW_LOADING_REQUEST = 'PROFILE_SHOW_LOADING_REQUEST';
export const PROFILE_SHOW_LOADING_SUCCESS = 'PROFILE_SHOW_LOADING_SUCCESS';

export const PROFILE_UPDATE_DATA_REQUEST = 'PROFILE_UPDATE_DATA_REQUEST';
export const PROFILE_UPDATE_DATA_SUCCESS = 'PROFILE_UPDATE_DATA_SUCCESS';

export const PROFILE_UPDATE_LOADING_REQUEST = 'PROFILE_UPDATE_LOADING_REQUEST';
export const PROFILE_UPDATE_LOADING_SUCCESS = 'PROFILE_UPDATE_LOADING_SUCCESS';
